leaning the data science and ml 

starting with the basic of numpy 

indexing numpy

In [1]:
#testing the jupter notebook 
import numpy as np 
a = np.array([5,6,9])
a[0]

5

In [2]:
a[1]

6

dimesioning in numpy

In [3]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [4]:
a = np.array([1,5,6,7])
a.ndim

1

btye size of the no. in numpy

In [5]:
a.itemsize

4

knowing the data type

In [6]:
a.dtype

dtype('int32')

changing the data type

In [7]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
a.itemsize

8

total no. of element in the array

In [8]:
a.size

6

shape of array 

In [9]:
a.shape

(3, 2)

intialize the complex no. with the array by the changing the data type

In [10]:
a = np.array([[1,2],[3,4],[5,6]], dtype=complex)
print(a)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


creating zeros array 

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

creating ones array eith the help of numpy

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

only ones and zeros array can be made in numpy and one empty set with random no.

range in numpy

In [13]:
i = range(5)
i

range(0, 5)

for printing the whole no between this to this no we can use np.arange

In [14]:
np.arange(1,5)

array([1, 2, 3, 4])

linspace create no. that are linearly spaced .
linspace in numpy it creates the random no. between the given syntax np.linspace(start,stop,num=)

In [15]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

reshaping the array

In [16]:
a=np.array([[1,2],[4,5],[5,6]])
a

array([[1, 2],
       [4, 5],
       [5, 6]])

In [17]:
a.shape

(3, 2)

In [18]:
a.reshape(2,3)

array([[1, 2, 4],
       [5, 5, 6]])

In [19]:
a.reshape(6,1)

array([[1],
       [2],
       [4],
       [5],
       [5],
       [6]])

to flatten your array or we can say make in one dim then we can we the ravel function to that

Ravel

In [20]:
a.ravel()

array([1, 2, 4, 5, 5, 6])

mathametical funtions in the numpy 

to print the  min and max value of the array then we can 
use the min and max function
a.min,a.max

In [21]:
a.min()

1

In [22]:
a.max()

6

sum of the array 

In [23]:
a.sum()

23

to add the no. by according to the rows and columns
we add the one function in the insert the a.sum() that is axis (0 is for columns and 1 for rows)

In [24]:
a.sum(axis=1)

array([ 3,  9, 11])

In [25]:
a.sum(axis=0)

array([10, 13])

sqrt in the numpy

In [26]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [2.        , 2.23606798],
       [2.23606798, 2.44948974]])

standard deviation  in the n numpy \
std:-Standard Deviation is a measure which shows how much variation (such as spread, dispersion) from the mean exists

In [27]:
np.std(a)

1.7716909687891083

additon, subtraction, multiplication, division in the numpy

In [28]:
a

array([[1, 2],
       [4, 5],
       [5, 6]])

In [29]:
b=np.array([[3,4],[4,3],[7,8]])

In [30]:
b

array([[3, 4],
       [4, 3],
       [7, 8]])

In [31]:
a+b

array([[ 4,  6],
       [ 8,  8],
       [12, 14]])

In [32]:
a-b

array([[-2, -2],
       [ 0,  2],
       [-2, -2]])

In [33]:
a*b

array([[ 3,  8],
       [16, 15],
       [35, 48]])

In [34]:
a/b

array([[0.33333333, 0.5       ],
       [1.        , 1.66666667],
       [0.71428571, 0.75      ]])

matrix prduct in the numpy 

In [35]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[5,6]])

In [36]:
a.dot(b)

array([[14, 17],
       [32, 39]])